version: 2.1
orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.1.1
jobs:
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
      - codecov/upload:
          file: coverage/coverage-final.json
      - store_artifacts:
          path: coverage

workflows:
  test-flow:
    jobs:
      - unit-test:
          filters:
            branches:
              ignore:
                - gh-pages
